spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-simulator-service
          predicates:
            - Path=/orders/**
  discovery:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/